# 1 stage build

FROM python:3.12-slim

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y gcc && \
    apt-get clean

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY ./app /app

EXPOSE 5000
WORKDIR /app

ENTRYPOINT gunicorn --bind 0.0.0.0:5000 main:app